### ISSUE TITLE
Useless assignment of local variable in Inventory::Collector

### ISSUE THREAD

**Issue by agrare** [Autosde/manageiq-providers-autosde#14]
e.g. https://github.com/Autosde/manageiq-providers-autosde/blob/master/app/models/manageiq/providers/autosde/inventory/collector/storage_manager.rb#L12

`system = system` doesn't actually do anything

**Comment by gregoryb-at-ibm** [comment]
It was the only way I could make IDEA to get the ruby type-hints to work. 
But it's all been removed anyway.

**Comment by agrare** [comment]
Fixed by https://github.com/Autosde/manageiq-providers-autosde/commit/b5f7ad708cd42a19088e4c503da4420028935831
