### ISSUE TITLE
OpenapiClient::VolumesApi shouldn't be in the autosde/storage_manager file

### ISSUE THREAD

**Issue by agrare** [Autosde/manageiq-providers-autosde#5]
There's already a TODO but we should track it here

https://github.com/Autosde/manageiq-providers-autosde/blob/master/app/models/manageiq/providers/autosde/storage_manager.rb#L291-L295

**Comment by gregoryb-at-ibm** [comment]
@agrare 
Since I changed the master, it's not longer clear which TODO this refers to.
