### ISSUE TITLE
The Autosde provider isn't built by the StorageManager

### ISSUE THREAD

**Issue by agrare** [Autosde/manageiq-providers-autosde#8]
There is a `ManageIQ::Providers::Autosde::Provider` but it doesn't appear to be built when creating the StorageManager so it wouldn't be created

**Comment by gregoryb-at-ibm** [comment]
I'm not clear on what the provider class actually does, and I was thinking that maybe we can delete it?

**Comment by agrare** [comment]
If you aren't planning on using the Provider class then yes you can delete it
